module.exports = {
  // Masters Tables
  MASTER_LOGIN: "master_login",
  ENTITY_CONFIGURATION: "tbl_entity_configuration",
  MASTER_ROLE: "master_role",
  MASTER_DEPARTMENT: "master_department",
  MASTER_DESIGNATION: "master_designation",
  MASTER_ALLOWANCE: "master_allowance",
  MASTER_AREA: "master_area",
  MASTER_BANK: "master_bank",
  MASTER_BRANCH: "master_branch",
  MASTER_COUNTRY: "master_country",
  MASTER_STATE: "master_state",
  MASTER_CITY: "master_city",
  MASTER_SHIFT: "master_shift",
  MASTER_UOM: "master_uom",
  MASTER_CONTRACT_TYPE: "master_contract_type",
  MASTER_COURSE_CATEGORY: "master_course_category",
  MASTER_EMPLOYMENT_TYPE: "master_employment_type",
  MASTER_EVENT_CATEGORY: "master_event_category",
  MASTER_ITEM_CATEGORY: "master_item_category",
  MASTER_ITEM: "master_item",
  MASTER_ITEM_SPECIFICATION: "master_item_specification",
  MASTER_SERVICE_CATEGORY: "master_service_category",
  MASTER_SERVICE: "master_service",
  MASTER_TICKET_CATEGORY: "master_ticket_category",
  MASTER_TRANSFER_REASON: "master_transfer_reason",
  MASTER_TRANSFER_TYPE: "master_transfer_type",

  // Hrms Tables
  HRMS_USER: "hrms_user",
  HRMS_USER_FAMILY_DETAIL: "hrms_user_family_detail",
  HRMS_USER_ALLOWANCE_MASTER: "hrms_user",
  HRMS_USER_PREVIOUS_EMPLOYER_DETAIL: "hrms_user",
  HRMS_USER_REGISTERED_ENTITY_MASTER: "hrms_user",
  HRMS_USER_SALARY_REVISION: "hrms_user",
};
